Repository discord/discord-api-docs, pull requests merged in 2022-09, with the labels that each got.

#5269 Add `INVITES_DISABLED` guild feature
  docs/resources/Guild.md
Labels: not released, communities

#5334 Add automod audit log types + fields
  docs/resources/Audit_Log.md
Labels: communities

#5397 The ML spam and mention spam AutoMod filters are out
  docs/resources/Auto_Moderation.md
Labels: communities

#5437 threads: message_count is affected by message creation time
  docs/resources/Channel.md
Labels: communities

#5458 Add note about new tags when modifying a forum channel: only `name` is required
  docs/resources/Channel.md
Labels: synced, communities
