Repository discord/discord-api-docs, pull requests merged in 2024-05, with the labels that each got.

#6584 Getting Started (DE) has been corrected a bit.
  docs/de/Getting_Started.mdx
Labels: localization

#5501 Remove outdated notice of interaction @everyone mention permissions
  docs/interactions/Receiving_and_Responding.md
Labels: waiting for response

#6864 add message.call field
  docs/resources/Channel.md
Labels: api

#6710 Add banner field in Modify Current User request
  docs/resources/User.md
Labels: api

#6834 chore: Migrate ESlint to flat config
  .eslintrc.json
  eslint.config.js
  package-lock.json
  package.json
Labels: waiting for response
